Added new comand line option -B <address> for binding specified address when connect to DNS server via TCP
zfl9/dns2tcp pull request #15
Opened 2024-06-18 10:49 UTC by ku4in

Added a new command line option -B <address>. This will allow you to configure traffic routing from dns2tsp through the desired network interface. Or even several copies of dns2tsp (listening on different UDP ports or bound to different network interfaces via the -L option) can be launched simultaneously with binding to different interfaces (by their IP addresses), which will allow routing traffic to the same DNS server (e.g. 8.8.8.8) through different network interfaces using the so-called policy-based routing. For these purposes, simply run several copies of the dns2tsp with different and -B <address> options, where <address> is the address of the desired network interface. And then use `ip route` and `ip rule` commands to route traffic to DNS server as you wish.

2024-06-27 09:42 UTC, zfl9 commented
Compilation failed.

2024-06-27 09:56 UTC, zfl9 requested changes

2024-06-27 09:56 UTC, zfl9 commented on dns2tcp.c
> +		    return 1;
Here it should `goto close_sockfd` instead of `return 1`.

2024-06-27 09:58 UTC, zfl9 commented on dns2tcp.c
> +    OPT_BIND_TCP    = 1 << 4,
Here it should be changed to `1 << 3`.

2024-06-27 10:20 UTC, ku4in commented
The requested changes have been made. Please review again.

2024-06-27 10:20 UTC, zfl9 commented on dns2tcp.c
> +	   " -B <ip>                 bind address for tcp connection\n"
Indents are not aligned.

2024-06-27 10:21 UTC, zfl9 commented on dns2tcp.c
> +	port = 0;
Indents are not aligned.

2024-06-27 10:21 UTC, zfl9 commented on dns2tcp.c
> +	if (portlen >= 0) log_info("Ignore port when binding address (set to zero)");
Indents are not aligned.

2024-06-27 10:22 UTC, zfl9 commented on dns2tcp.c
> +            case 1:
Indents are not aligned.

2024-06-27 10:27 UTC, zfl9 commented on dns2tcp.c
> +		break;
Indents are not aligned.

2024-06-27 10:28 UTC, zfl9 commented on dns2tcp.c
> +
Unnecessary blank lines.

2024-06-27 11:22 UTC, ku4in commented
The indents have been aligned and unnecessary empty lines have been removed. Please review again.

2024-06-27 11:35 UTC, zfl9 commented on dns2tcp.c
> +                    printf("invalid remote addr: %s\n", optarg);
`invalid remove addr` => `invalid bind addr`

2024-06-27 11:37 UTC, zfl9 commented on dns2tcp.c
> +    if has_opt(OPT_BIND_TCP) log_info("tcp  bind  addr: %s#%hu", g_bind_ipstr, g_bind_port);
`tcp bind addr` (remove extra spaces)

2024-06-27 11:40 UTC, zfl9 commented on dns2tcp.c
> +    }
Add a blank line above `if (connect(...)) {` to separate the two statement blocks.

2024-06-27 12:22 UTC, ku4in commented
Typos have been corrected. Please review again.

2024-06-27 12:29 UTC, zfl9 commented
Ok, I need to test locally to see if it compiles, and other REVIEW comments.

Sorry for the week-long gap in processing this PR, as I've been busy with work lately.

2024-06-27 12:38 UTC, ku4in commented
Thanks for the review! I hope the suggested changes are found useful and added to the project.

2024-07-10 09:29 UTC, merged

2024-07-10 09:29 UTC, zfl9 commented
Merged, thanks.